Cham review
canonical/digest-squid-auth-helper pull request #8
Opened 2024-12-19 16:22 UTC by seb4stien

PR to discuss on the charm review before publication.

2025-01-13 11:46 UTC, reneradoi commented
Hello @seb4stien could you please add me as a reviewer to this PR? I will conduct the review as part of your request to list this charm in charmhub.

Thank you!
René

2025-01-13 12:33 UTC, seb4stien commented
You should have review access now.

2025-01-13 16:58 UTC, reneradoi requested changes
Hello @seb4stien!

I've conducted the review for the Charmhub listing. In general, the repo, docs, code and automation look pretty good, and I don't have any major concerns.

There are two topics though that I would like to bring up, just to create some awareness and make sure you don't get trapped here:

1) The maintenance status for the `passlib` module is [highly questionable](https://foss.heptapod.net/python-libs/passlib/-/issues/187). There haven't been updates for more than 4 years, and it has some deprecations that you can already see in the warnings of the unit test runs ([example](https://github.com/canonical/digest-squid-auth-helper/actions/runs/12416673574/job/34665856448?pr=8#step:6:75)). As you only seem to be using it for password generation, I would recommend to move away from that module and - as a suggestion - generate your password with `secrets` module. An example for this can be found [here](https://github.com/canonical/zookeeper-operator/blob/main/src/workload.py#L144).

2) Another [deprecation warning](https://github.com/canonical/digest-squid-auth-helper/actions/runs/12416673574/job/34665856448?pr=8#step:6:80) I saw is related to the `harness` unit test framework. The charm ops team has made efforts to replace it with a tool called `Scenario`, and I would recommend to switch to this rather sooner than later. The approach is a little different, but the [docs](https://ops.readthedocs.io/en/latest/reference/ops-testing.html) are pretty good.

Please let me know if you need more information on those topics.

As for the listing, I would suggest that you replace the `passlib` usage, as this should be not too much effort required. The replacement of `harness` can be postponed to later I'd say.

2025-01-14 09:42 UTC, seb4stien commented
Thanks for the feedback. I will implement the change regarding passlib. For the transition from Harness to Scenario I feel this will be part of another effort we have to coordinate at the team level.

2025-01-15 09:48 UTC, reneradoi commented
Hey, after digging for some time, I found a fork of `passlib` called `libpass` [here](https://github.com/ThirVondukr/passlib). Maybe this would be an alternative? It is actively maintained and supports current platforms and versions.

2025-01-16 17:29 UTC, seb4stien commented
Thanks for checking. I saw this one, but I was hesitant as it's quite new (first release in September if I read it correctly).

I tried and it works. So if it's preferable for you to go for this one I'm good with it.

2025-01-17 07:28 UTC, reneradoi commented
Hey @seb4stien , I'm fine with either. My main goal was to raise your awareness on these topics, to avoid critical dependency on deprecated packages. If you decide to wait for a bit before jumping on to `libpass` to see it establishing, that's ok.

I think we've made good progress in discussing possible solutions, so we can move on here and I will also finish the review on the charmhub forum now.

Thank you!
René

2025-01-17 07:29 UTC, reneradoi approved these changes
Possible alternatives for the deprecated dependencies have been discussed, implementation will be coordinated by the team independently.

No further concerns from my side.

2025-01-20 08:26 UTC, seb4stien commented
The changes have been merged to main, what are the next steps:
- here => can I close the PR?
- on charmhub, should I do anything to get the charm listed?

2025-01-20 10:50 UTC, reneradoi commented
@seb4stien Yes, you can close this PR. On Charmhub I've added the checklist that is required to have a charm listed. I will ping the team to follow up on what comes next.

2025-01-20 11:18 UTC, closed without merging